scrape_configs:
  - job_name: "Webshop input"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 15s
    scheme: https
    static_configs:
      - targets: ["host.docker.internal:8081"]
        labels:
          application: "Webshop"
    tls_config:
      insecure_skip_verify: true

  - job_name: "PSP input"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 15s
    scheme: https
    static_configs:
      - targets: ["host.docker.internal:8082"]
        labels:
          application: "PSP"
    tls_config:
      insecure_skip_verify: true

    # Container metrics (needed for the Docker dashboard)
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # Host metrics (optional)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
