PAYPAL_API_BASE = "https://api-m.sandbox.paypal.com"
PAYPAL_BASE_URL = "https://localhost:8087"
PAYPAL_RETURN_URL = f"{PAYPAL_BASE_URL}/paypal/return/"
PAYPAL_SUBSCRIPTION_RETURN_URL = f"{PAYPAL_BASE_URL}/paypal/return/subscription/"
PAYPAL_CANCEL_URL = f"{PAYPAL_BASE_URL}/paypal/cancel/"