server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: 'Webshop'
    static_configs:
      - targets:
          - localhost
        labels:
          job: webshop
          __path__: /logs/webshop.log
  - job_name: 'PSP'
    static_configs:
      - targets:
          - localhost
        labels:
          job: psp
          __path__: /logs/psp.log